export const RESET_REQUEST = 'RESET_REQUEST';

// Boards
export const START_GET_BOARDS = 'START_GET_BOARDS';
export const SUCCESS_GET_BOARDS = 'SUCCESS_GET_BOARDS';
export const ERROR_GET_BOARDS = 'ERROR_GET_BOARDS';
export const START_GET_MEMBERS_BY_BOARD_ID = 'START_GET_MEMBERS_BY_BOARD_ID';
export const SUCCESS_GET_MEMBERS_BY_BOARD_ID = 'SUCCESS_GET_MEMBERS_BY_BOARD_ID';
export const ERROR_GET_MEMBERS_BY_BOARD_ID = 'ERROR_GET_MEMBERS_BY_BOARD_ID';